version: "3.8"

services:
  postgres:
    image: postgis/postgis:15-3.3
    container_name: juris-postgres
    environment:
      POSTGRES_DB: juris_db
      POSTGRES_USER: juris_user
      POSTGRES_PASSWORD: juris_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/database/init.sql:/docker-entrypoint-initdb.d/001_init.sql
      - ./backend/database/migrations/002_capture_paths.sql:/docker-entrypoint-initdb.d/002_capture_paths.sql
      - ./backend/database/migrations/003_game_mechanics.sql:/docker-entrypoint-initdb.d/003_game_mechanics.sql
      - ./backend/database/migrations/004_realtime_tracking.sql:/docker-entrypoint-initdb.d/004_realtime_tracking.sql
      - ./backend/database/migrations/005_team_ownership.sql:/docker-entrypoint-initdb.d/005_team_ownership.sql
      - ./backend/database/migrations/005_chat_system.sql:/docker-entrypoint-initdb.d/006_chat_system.sql
      - ./backend/database/migrations/008_gamification_system.sql:/docker-entrypoint-initdb.d/008_gamification_system.sql
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: juris-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
