version: '3.8'

services:
  postgres:
    image: postgis/postgis:15-3.3
    container_name: juris-postgres
    environment:
      POSTGRES_DB: juris_db
      POSTGRES_USER: juris_user
      POSTGRES_PASSWORD: juris_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: juris-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
