ALTER TABLE user_streaks 
ADD COLUMN IF NOT EXISTS weekly_streak INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS monthly_streak INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS last_updated TIMESTAMP DEFAULT NOW();
